"""Initial migration.

Revision ID: f28588d176d7
Revises: 
Create Date: 2024-06-23 22:18:11.637446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28588d176d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encomenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilizadorId', sa.Integer(), nullable=True),
    sa.Column('aberta', sa.Boolean(), nullable=True),
    sa.Column('morada', sa.String(length=255), nullable=True),
    sa.Column('tracking_number', sa.String(length=21), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_number')
    )
    op.create_table('encomenda_linha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encomendaId', sa.Integer(), nullable=True),
    sa.Column('artigoId', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['encomendaId'], ['encomenda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encomenda_linha')
    op.drop_table('encomenda')
    # ### end Alembic commands ###
