"""email

Revision ID: c8ed7e5c247f
Revises: 236214666249
Create Date: 2024-06-16 11:11:29.160452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ed7e5c247f'
down_revision = '236214666249'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('utilizador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint('uq_utilizador_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilizador', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
